config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  def index
    @kittens = Kitten.all
    
    respond_to do |f|
      f.html
      f.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
  
    respond_to do |f|
      f.html
      f.json { render :json => @kitten }
    end
  end
  
  def new
    @kitten = Kitten.new
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:notice] = "New kitten saved!"
      redirect_to @kitten
    else
      flash[:alert] = "Meow meow, thats not correct"
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      flash[:notice] = "New kitten updated!"
      redirect_to @kitten
    else
      flash[:alert] = "Meow meow, no updates for you"
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    flash[:notice] = "Cat goes bye bye"
    redirect_to root_path, status: :see_other
  end

  private

  def kitten_params
    params.required(:kitten).permit(:name, :age, :cuteness, :softness)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |type,msg|%>
    <div> <%= msg%></div>
  <% end %>
<% end %>

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |kitten|%>
  Kitten's Name: <%= kitten.text_field :name, required: true%><br>
  Youngness(age):  <%= kitten.number_field :age, required: true %><br>
  Cuteness(#1-10):  <%= kitten.number_field :cuteness, required: true %><br>
  Softness(#1-10): <%= kitten.number_field :softness , required: true %><br><br>

  <%= kitten.submit "Save Kitten"%>
<% end %>

app/views/kittens/index.html.erb
<%= render "flash"%>

<h1>All Kittens All The Time</h1>
<ul>
  <% @kittens.each do |kitten| %>
    <li> 
      Name: <%= link_to  kitten.name, kitten %> <br>
      Age: <%= kitten.age %> <br>
      Cuteness: <%= kitten.cuteness %> <br>
      Softness: <%= kitten.softness %> <br>
      <%= link_to "Delete me?", kitten_path(kitten), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this kitten? This cannot be undone" } %> <br><br> 
    </li>
  <% end %>
</ul>

<%= link_to "Add a new kitten", "/kittens/new" %>

app/views/kittens/new.html.erb
<%= render "flash" %>

<h1>Add a Kitten</h1>

<%= render "form"%><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>